name: apexml
version: '1.0.0'
config-version: 2

profile: apexml

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  apexml:
    staging:
      +schema: STAGING
      +materialized: view
    marts:
      +schema: PROD
      +materialized: table
      +transient: false
