import os

SNOWFLAKE_ACCOUNT = os.environ["SNOWFLAKE_ACCOUNT"]
SNOWFLAKE_USER = os.environ["SNOWFLAKE_USER"]
SNOWFLAKE_PRIVATE_KEY_PATH = os.environ["SNOWFLAKE_PRIVATE_KEY_PATH"]
SNOWFLAKE_DATABASE = os.environ.get("SNOWFLAKE_DATABASE", "APEXML_DB")
SNOWFLAKE_SCHEMA = os.environ.get("SNOWFLAKE_SCHEMA", "RAW")
SNOWFLAKE_WAREHOUSE = os.environ.get("SNOWFLAKE_WAREHOUSE", "APEXML_WH")
SNOWFLAKE_ROLE = os.environ.get("SNOWFLAKE_ROLE", "APEXML_WRITER")

OPENF1_BASE_URL = "https://api.openf1.org/v1"
